import React from 'react'

const TermsAndCondition = () => {
    return (
        <div className='p-16 bg-white w-full'>
            <h1 className='text-[32px] font-medium'>Terms and Condition</h1>
            <h2 className='text-[18px] font-medium mt-5'>Introduction</h2>
            <p className='text-[16px]'>Welcome to the marfit.in brought to you by MARFIT. In using the marfit.in service, of MARFIT you are deemed to have accepted the terms and conditions listed below. All products/services and information displayed on marfit.in constitute an 'invitation to offer'. Your order for purchase constitutes your 'offer' which shall be subject to the terms and conditions as listed below. marfit.in reserves the right to accept or reject your offer. If you have supplied us with your valid email address, we will notify you by email as soon as possible to confirm receipt of your order and email you again to confirm details and therefore process the order. Our acceptance of your order will take place upon dispatch of the product(s) ordered. No act or omission of marfit.in prior to the actual dispatch of the product(s) ordered will constitute acceptance of your offer.</p>
            <h2 className='text-[18px] font-medium mt-5'>Membership Eligibility:</h2>
            <p className='text-[16px]'>Use of the Site is available only to persons who can form legally binding contracts under applicable law. Persons who are 'incompetent to contract' within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Site. If you are a minor i.e. under the age of 18 years but at least 13 years of age you may use this Site only under the supervision of a parent or legal guardian who agrees to be bound by these Terms of Use. If your age is below that of 18 years your parents or legal guardians can transact on behalf of you if they are registered users. You are prohibited from purchasing any material which is for adult consumption the sale or purchase of which to/by minors are strictly prohibited. marfit.in reserves the right to terminate your membership and refuse to provide you with access to the Site if marfit.in discovers that you are under the age of 18 years. The Site is not available to persons whose membership has been suspended or terminated by Marfit.in for any reason whatsoever. If you are registering as a business entity, you represent that you have the authority to bind the entity to this User Agreement. Unless otherwise specified, the materials on this website are directed solely at those who access this website from India. marfit.in makes no representation that any products or services referred to in the materials on this website are appropriate for use, or available outside India. Those who choose to access this Site from outside India are responsible for compliance with local laws if and to the extent local laws are applicable. marfit.in will deliver the products only within India and will not be liable for any claims relating to any products ordered from outside India. Except where additional terms and conditions are provided which are product specific, these terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the services of marfit.in you agree to be bound by the Terms and Conditions.</p>
            <h2 className='text-[18px] font-medium mt-5'>User Identity and Password:</h2>
            <p className='text-[16px]'>If you use marfit.in you shall be responsible for maintaining the confidentiality of your User ID and Password and you shall be responsible for all activities that occur under your User ID and Password. You agree that if you provide any information that is untrue, inaccurate, not current or incomplete or marfit.in has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, marfit.in has the right to indefinitely suspend or terminate or block access of your membership with marfit.in.</p>

        </div>
    )
}

export default TermsAndCondition